apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: X.Web.Sitemap.NNet
  description: NNet modified version of X.Web.Sitemap
  annotations:
    dev.azure.com/project: NNet
    dev.azure.com/build-definition: tsteele.X.Web.Sitemap
  links:
    - title: Derived from X.Web.Sitemap
      url: https://github.com/a-gubskiy/X.Web.Sitemap
  tags:
    - net8
spec:
  type: package
  owner: nnet
  lifecycle: test